export enum Routes {
    INITIAL = '/',
    HOME = 'home',
    LISTING = 'listing',
    INDIVIDUAL_LISTING = 'listing/:id',
    ACCOUNT = 'account',
    CREATE_ACCOUNT = 'account/create',
    EDIT_ACCOUNT = 'account/edit',
    ALL_MY_LISTINGS = 'listing/all-my-listings',
    MY_LISTINGS = 'listing/my-listings',
    CREATE_LISTINGS = 'listing/create',
    EDIT_LISTINGS = 'listing/edit',
    EDIT_LISTINGS_IMAGE_UPLOAD = 'listing/edit/image-upload',
    LANDING = 'landing',
    REGISTER = 'register',
    LOG_IN = 'log-in',
    FAQ = 'faq',
    ANYTHING_ELSE = '*',
}