export enum Routes {
  INITIAL = "/",
  HOME = "/home",
  LISTING = "/listings",
  INDIVIDUAL_LISTING = "/listing/:id",
  ACCOUNT = "/account",
  AUTHENTICATE = "/authenticate",
  CREATE_ACCOUNT = "/account/create",
  EDIT_ACCOUNT = "/account/edit",
  ALL_MY_LISTINGS = "/my-listings",
  MY_LISTING = "/my-listings/listing",
  CREATE_LISTINGS = "/listing/create",
  EDIT_LISTINGS = "/listing/:id/edit",
  Community_Guidelines = "/listing/edit/image-upload",
  LANDING = "/landing",
  REGISTER = "/register",
  LOG_IN = "/log-in",
  FAQ = "/faq",
  COMMUNITY_GUIDELINES = "/community-guildelines",
  COOKIE_POLICY = "/cookie-policy",
  MOBILE_TERMS_OF_USE = "/mobile-terms-of-use",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_OF_USE = "/terms-of-use",
  ABOUT_US = "/about-us",
  CAREERS = "/careers",
  ANYTHING_ELSE = "*",
}
